export { default as LoginView } from './LoginView.vue'
export { default as RegisterView } from './RegisterView.vue'
export { default as ForgotPasswordView } from './ForgotPasswordView.vue'
export { default as ResetPasswordView } from './ResetPasswordView.vue'
export { default as SessionsView } from './SessionsView.vue'
