// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Shared.Operational.Persistence.Data;

#nullable disable

namespace Api.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721000000_AddVectorIVFFlatIndex")]
    partial class AddVectorIVFFlatIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.3");
#pragma warning restore 612, 618
        }
    }
}
