import { inventoryApi } from './inventory.api'

export const inventoryService = {
  listStocks: inventoryApi.stocks.list,
  getStockDetail: inventoryApi.stocks.getById,
  createStock: inventoryApi.stocks.create,
  restock: inventoryApi.stocks.restock,
  deleteStock: inventoryApi.stocks.delete,
  getLowStock: inventoryApi.stocks.getLowStock,
  getStockSummary: inventoryApi.stocks.getSummary,
  bulkAdjust: inventoryApi.stocks.bulkAdjust,
  listLocations: inventoryApi.locations.list,
  getLocationDetail: inventoryApi.locations.getById,
  createLocation: inventoryApi.locations.create,
  updateLocation: inventoryApi.locations.update,
  deleteLocation: inventoryApi.locations.delete,
  setDefaultLocation: inventoryApi.locations.setDefault,
  listReservations: inventoryApi.reservations.list,
  getReservationDetail: inventoryApi.reservations.getById,
  cancelReservation: inventoryApi.reservations.cancel,
  listTransfers: inventoryApi.transfers.list,
  getTransferDetail: inventoryApi.transfers.getById,
  createTransfer: inventoryApi.transfers.create,
  transferStock: inventoryApi.transfers.transfer,
  receiveTransfer: inventoryApi.transfers.receive,
  cancelTransfer: inventoryApi.transfers.cancel,
  listMovements: inventoryApi.movements.list,
  getMovementDetail: inventoryApi.movements.getById,
}
