import { inventoryApi } from './inventory.api'

export const inventoryService = {
  listStocks: inventoryApi.stocks.list,
  getStockDetail: inventoryApi.stocks.getById,
  adjustStock: inventoryApi.stocks.adjust,
  auditStock: inventoryApi.stocks.audit,
  updateBackorderPolicy: inventoryApi.stocks.updateBackorderPolicy,
  deleteStock: inventoryApi.stocks.delete,
  listInventoryUnits: inventoryApi.units.list,
  getInventoryUnitDetail: inventoryApi.units.getById,
  updateInventoryUnitSerialNumber: inventoryApi.units.updateSerialNumber,
  markInventoryUnitDamaged: inventoryApi.units.markDamaged,
  restoreInventoryUnit: inventoryApi.units.restore,
  listMovements: inventoryApi.movements.list,
  listLocations: inventoryApi.locations.list,
  getLocationTree: inventoryApi.locations.getTree,
  getLocationDetail: inventoryApi.locations.getById,
  createLocation: inventoryApi.locations.create,
  updateLocation: inventoryApi.locations.update,
  deleteLocation: inventoryApi.locations.delete,
  toggleLocationStatus: inventoryApi.locations.toggleStatus,
  listTransfers: inventoryApi.transfers.list,
  getTransferDetail: inventoryApi.transfers.getById,
  createTransfer: inventoryApi.transfers.create,
  addTransferItem: inventoryApi.transfers.addItem,
  shipTransfer: inventoryApi.transfers.ship,
  receiveTransfer: inventoryApi.transfers.receive,
  cancelTransfer: inventoryApi.transfers.cancel,
}