/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Tree: typeof import('primevue/tree')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}

// For TSX support
declare global {
  const Avatar: typeof import('primevue/avatar')['default']
  const Badge: typeof import('primevue/badge')['default']
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const Chart: typeof import('primevue/chart')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const Column: typeof import('primevue/column')['default']
  const ConfirmDialog: typeof import('primevue/confirmdialog')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const Divider: typeof import('primevue/divider')['default']
  const Drawer: typeof import('primevue/drawer')['default']
  const Dropdown: typeof import('primevue/dropdown')['default']
  const FileUpload: typeof import('primevue/fileupload')['default']
  const IconField: typeof import('primevue/iconfield')['default']
  const Image: typeof import('primevue/image')['default']
  const InputIcon: typeof import('primevue/inputicon')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputSwitch: typeof import('primevue/inputswitch')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const MultiSelect: typeof import('primevue/multiselect')['default']
  const OverlayPanel: typeof import('primevue/overlaypanel')['default']
  const Password: typeof import('primevue/password')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('primevue/select')['default']
  const SelectButton: typeof import('primevue/selectbutton')['default']
  const Skeleton: typeof import('primevue/skeleton')['default']
  const Tab: typeof import('primevue/tab')['default']
  const TabList: typeof import('primevue/tablist')['default']
  const TabPanel: typeof import('primevue/tabpanel')['default']
  const TabPanels: typeof import('primevue/tabpanels')['default']
  const Tabs: typeof import('primevue/tabs')['default']
  const Tag: typeof import('primevue/tag')['default']
  const Textarea: typeof import('primevue/textarea')['default']
  const Timeline: typeof import('primevue/timeline')['default']
  const Toast: typeof import('primevue/toast')['default']
  const ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  const Tree: typeof import('primevue/tree')['default']
  const TreeTable: typeof import('primevue/treetable')['default']
}