= Background and Related Work

#include "ch1-background/00-chapter.typ"
#include "ch1-background/01-vector-embeddings.typ"
#include "ch1-background/02-dl-architectures.typ"
#include "ch1-background/03-vector-databases.typ"
#include "ch1-background/04-ecommerce-architectures.typ"
#include "ch1-background/05-related-work.typ"
#include "ch1-background/06-dotnet-backend.typ"
#include "ch1-background/07-vue-frontend.typ"
#include "ch1-background/08-postgresql-pgvector.typ"
#include "ch1-background/09-redis-caching.typ"
#include "ch1-background/10-python-ml-sidecar.typ"
#include "ch1-background/11-aspire-orchestration.typ"
#include "ch1-background/12-hangfire-jobs.typ"
#include "ch1-background/13-identity-auth.typ"
#include "ch1-background/14-benchmark-framework.typ"
#include "ch1-background/15-technology-summary.typ"
