= Implementation

This chapter describes the concrete realisation of the ReSys.Shop system architecture presented in Chapter 4. The chapter is organised into five sections, progressing from the architectural pattern that structures the codebase, through the machine learning pipeline that constitutes the core research contribution, to the end-to-end visual search flow and its configuration mechanism, and finally a concise survey of the supporting e-commerce modules. The implementation follows the service-oriented design established in the previous chapter: a Vue 3 frontend, a .NET 10 modular monolith backend, and a Python machine learning sidecar, each implemented in the technology most appropriate for its domain.

== Vertical Slice Architecture

The .NET backend is organised according to *Vertical Slice Architecture* (VSA), a pattern in which code is grouped by business capability rather than by technical layer. In a traditional layered architecture, all data access classes reside in one project, all business logic in another, and all web controllers in a third. VSA inverts this convention: all code required to fulfil a single feature, the request, the handler, the response, the validator, is co-located within one directory. This organisation makes the system easier to navigate because a developer tracing a feature through the codebase follows a vertical path rather than jumping across four or five horizontal layers.

The implementation uses Carter minimal APIs for route registration and MediatR for command and query dispatch. Each bounded context, Catalog, Ordering, Payment, and the remaining five modules, contributes its own `ICarterModule` implementation, which registers all endpoints belonging to that context. Endpoints are thin: they extract parameters from the HTTP request, construct a MediatR command or query object, dispatch it through `ISender`, and map the resulting `Result<T>` to an HTTP status code and JSON body. All business logic, database access, and domain invariant enforcement reside in the handler layer, where they are testable without HTTP infrastructure.

FluentValidation ensures that every command and query object is validated before its handler executes. Validation classes live alongside the handlers they protect, keeping the validation rules visible and colocated with the logic they guard. The MediatR pipeline wraps each request with three behaviours, validation, logging, and exception mapping, applied automatically to every handler in the system. A fourth pipeline behaviour enforces feature-level transaction boundaries, ensuring that handlers operating on multiple database rows do so within a single unit of work.

The vertical slice organisation enforces a strict module boundary rule: no bounded context may import another context's namespace. All inter-module communication flows through MediatR's `ISender` interface. A context may dispatch a query to another context or publish a notification that other contexts react to, but it may never reference a class, type, or namespace belonging to another module. This constraint preserves the logical isolation of the bounded contexts, the same isolation that would be enforced by network boundaries in a microservices architecture, while retaining the deployment simplicity of a single process.

== ML Embedding Pipeline

The Python machine learning sidecar is the core research contribution of this thesis. It is a specialised AI service responsible for generating high-dimensional vector embeddings from product images, exposing endpoints consumed by the .NET backend through HTTP. This section describes the internal architecture, the model loading strategy, the embedding generation flow, and the health monitoring mechanism.

=== Service Architecture

The ML sidecar is built on Python 3.12 with the FastAPI framework and runs under the Uvicorn ASGI server. Its internal architecture follows a three-layer design:

- The *FastAPI interface layer* handles HTTP concerns: routing requests to the correct endpoint, validating the API key presented in the `X-API-Key` header, parsing multipart form data containing image bytes, and serialising embedding results to JSON. This layer contains no machine learning logic.

- The *Model Manager layer* is a singleton service responsible for the lifecycle of deep learning models. It maintains a registry of loaded models, loads new models on demand, caches them in GPU or CPU memory, and dispatches inference requests to the correct model instance. The singleton pattern ensures that a single copy of each model, typically consuming several gigabytes of VRAM, serves all inbound requests.

- The *PyTorch Runtime layer* is the hardware-facing component that executes forward passes through the neural network. It handles device placement, selecting CUDA for NVIDIA GPUs, MPS for Apple Silicon, or CPU as a fallback, and manages the tensor operations that convert raw image data into embedding vectors.

The service exposes two endpoints: `POST /embeddings`, which accepts image bytes and returns a 512-dimensional float vector, and `GET /health`, which reports the operational status of the underlying hardware and loaded models. The service is containerised as a Docker image and orchestrated by .NET Aspire, which manages service discovery, the backend addresses the ML sidecar as `http://ml-service` on the internal Docker network, and health-check restarts.

=== Model Loading Strategy

The ML sidecar employs a *lazy loading* strategy to optimise resource utilisation. Deep learning models are not loaded at service startup, when they would consume gigabytes of GPU memory before the first request arrives. Instead, models are loaded upon their first invocation, when the .NET backend sends an image to be embedded for the first time, the Model Manager instantiates the configured model, loads its weights into memory, and caches the instance for all subsequent requests.

The Model Manager implements the *Strategy Pattern*: each model conforms to a common interface with a standard `generate_embedding(image_bytes)` method, and the manager selects the active model based on the `EMBEDDING_MODEL` environment variable. Changing models requires only a configuration change and a service restart, no code changes. The Model Manager maintains an internal dictionary-style cache keyed by model name, so a request for a previously loaded model returns the cached instance immediately.

The supported models span four architectural families. *Convolutional neural networks* are represented by ResNet-50 (2048-dimensional output) and EfficientNet-B0 (1280-dimensional), both pre-trained on ImageNet and serving as lightweight feature extractors. *Vision transformers* include DINOv2 ViT-S/14 (384-dimensional) and DINOv2 ViT-B/14 (768-dimensional), leveraging self-supervised pre-training that requires no labelled data. *CLIP-based models*, CLIP ViT-B/32, CLIP ViT-B/16, and CLIP ViT-L/14, produce 512-dimensional embeddings in a shared text-image latent space, enabling multimodal search where a text query can find visually similar products. *Fashion-specific models* are represented by Fashion-CLIP, a CLIP variant fine-tuned on over 700 000 fashion images with domain-specific vocabulary, also producing 512-dimensional vectors.

=== Embedding Generation Flow

The embedding generation process follows a precise pipeline from image reception to vector output. Figure @fig-ml-pipeline illustrates this flow.

#figure(
  image("../../images/diagrams/11-ml-pipeline.png", width: 100%),
  caption: [ML embedding pipeline: the step-by-step flow from image bytes received by the FastAPI interface to a 512-dimensional float vector returned as JSON to the .NET backend.],
) <fig-ml-pipeline>

The pipeline comprises seven sequential steps. The .NET backend initiates the process by sending raw image bytes to the `POST /embeddings` endpoint. The FastAPI interface validates the `X-API-Key` header against the expected key and rejects unauthorised requests with a 401 response. The Model Manager retrieves the currently configured model from its cache, loading it from disk on the first request, and dispatches the image payload to the model's preprocessing pipeline.

The preprocessing stage normalises the input image to the format expected by the selected model. The image is resized to the model's expected input dimensions, 224 by 224 pixels for most architectures, and converted from interleaved colour channels to separated channel tensors. ImageNet-normalisation statistics are applied: each colour channel is centred to the ImageNet mean and scaled by the standard deviation, matching the distribution on which the model was originally trained.

The preprocessed tensor is passed through the model's forward pass. For convolutional models, this involves a cascade of convolution, activation, and pooling operations that extract hierarchical features. For transformer-based models, the image is divided into patches, each patch is projected into a token embedding, and self-attention layers compute contextual relationships between patches across the entire image. The output of the forward pass is pooled, typically via global average pooling, to produce a single fixed-length vector regardless of the original image size.

The resulting vector is a 512-dimensional array of single-precision floating-point numbers (for CLIP-family models; other dimensionalities for other architectures). This vector encodes the visual essence of the image, colour palette, texture patterns, silhouette shape, and semantic category, in a compressed numerical form suitable for similarity computation. The vector is serialised to a JSON array and returned to the .NET backend as the response body, together with metadata fields identifying the model name and generation time in milliseconds.

=== Health Monitoring

The `/health` endpoint provides a comprehensive operational status for the Aspire orchestration layer. It verifies three conditions: that the GPU environment is active and accessible, confirming CUDA or MPS availability; that the configured model is successfully loaded into memory and ready for inference; and that a baseline inference pass completes without errors, validating the entire pipeline from preprocessing to output generation. The health response includes diagnostic data, model load status, last inference time, GPU memory utilisation, enabling the orchestrator to detect degraded states and trigger Docker restart policies automatically without human intervention.

== CBIR Search Flow

The content-based image retrieval search flow is the primary user-facing capability enabled by the ML embedding pipeline. It spans four system components, the Vue 3 storefront, the .NET API backend, the Python ML sidecar, and PostgreSQL with pgvector, and must complete in under one second to remain viable as a real-time feature. Figure @fig-cbir-sequence depicts the full cross-service interaction.

#figure(
  image("../../images/diagrams/12-cbir-search-sequence.png", width: 100%),
  caption: [CBIR search sequence: the complete end-to-end flow from customer image upload through embedding generation and vector search to ranked results display, spanning the Vue frontend, .NET API, Python ML sidecar, and PostgreSQL pgvector.],
) <fig-cbir-sequence>

The flow begins when a customer uploads an image through the Vue storefront interface. The client performs an initial validation pass, checking that the file type is JPEG, PNG, or WebP and that the file size does not exceed ten megabytes, and presents immediate feedback if the upload fails these checks. Upon passing client-side validation, the image is sent as a multipart form data request to the `POST /api/catalog/storefront/search-by-image` endpoint on the .NET backend.

The backend performs a second, stricter validation pass. It verifies the file's magic bytes, the binary header signature of a valid image file, rather than trusting the file extension, which a malicious client could forge. It confirms the MIME type and enforces the same ten-megabyte size limit server-side. If validation passes, the backend sends the raw image bytes to the Python ML sidecar's `/embeddings` endpoint with the `X-API-Key` header.

The ML sidecar executes the embedding pipeline described in Section 5.2.3, preprocessing, model inference, vector output, and returns a 512-dimensional float vector together with the model name metadata. The backend now holds a numerical representation of the customer's image that can be compared against every product image in the catalogue.

The vector search query executes against the `variant_images` table in PostgreSQL. The query computes the cosine distance between the query embedding and every stored embedding using the `<=>` operator provided by the pgvector extension, orders results by ascending distance, and returns the closest matches. An HNSW index on the embedding column reduces the search complexity to logarithmic time, sub-ten milliseconds on a corpus of tens of thousands of images. The query includes a `model_name` filter, ensuring that only embeddings generated by the currently active model participate in the comparison; cross-model vector comparisons would produce meaningless results because different models embed images into different latent spaces.

The backend assembles the results into a search response. It joins the top-matching variant image rows with their parent variant and product records to retrieve titles, pricing, and thumbnail URLs. It converts cosine distances into similarity scores, computed as one minus the distance, and filters out results below a configurable minimum similarity threshold, defaulting to 0.7. In fashion image retrieval, a cosine similarity of 0.7 typically corresponds to perceptible visual similarity, while values above 0.9 indicate near-identical items. A product may appear multiple times in the results if multiple of its variant images matched the query, but the response deduplicates by product and returns the highest-scoring match per product.

The backend returns a JSON array of matching products to the Vue storefront. Each entry includes the product title, the matched variant's thumbnail URL, the selling price, the similarity score expressed as a percentage, and a product URL for navigation. The Vue frontend renders these results as a grid of product cards with thumbnail images, price labels, and similarity score badges, completing the search experience. The total end-to-end latency, from upload to rendered results, is designed to remain under one second, with the model inference typically accounting for fifty to one hundred milliseconds of that budget depending on the active model.

== Model Configuration

The ability to switch between embedding models without code changes is a key implementation decision that supports the benchmark evaluation presented in Chapter 6. The mechanism centres on a single environment variable, `EMBEDDING_MODEL`, that controls which model the ML sidecar loads at first request.

The environment variable accepts a short model identifier: `fashion_clip` for the fine-tuned fashion model, `resnet50` for the classic CNN baseline, `efficientnet_b0` for the lightweight scaled CNN, `clip_vit_b32` or `clip_vit_b16` or `clip_vit_l14` for general-purpose CLIP variants, and `dinov2_vits14` or `dinov2_vitb14` for self-supervised vision transformers. When the Model Manager receives its first embedding request, it reads this variable, instantiates the corresponding model class, loads weights from disk, and caches the instance. Subsequent requests are served from the cache. Changing the active model requires updating the environment variable and restarting the container, a configuration-only change with no code modification.

Each stored embedding carries two metadata columns: `model_name`, identifying which model generated the vector, and `model_version`, capturing the weight snapshot used. When the backend queries pgvector for similar images, it filters by `model_name`, only embeddings from the currently active model participate in the search. This filter ensures that the system can store embeddings from multiple models simultaneously, with each model's embeddings occupying a separate conceptual index within the same physical column. After switching the active model, newly uploaded images begin generating embeddings under the new model name, while existing embeddings under the old model name remain available but are excluded from search queries.

This configuration mechanism enables the benchmark workflow that Chapter 6 depends on. Eleven models are evaluated against the same image corpus by loading each model in sequence, generating embeddings for the full query and catalogue image sets, running the retrieval evaluation protocol, and recording the results, all without modifying application code. In production, the same mechanism enables A/B testing: two instances of the ML sidecar, each configured with a different model, serve embedding requests to different user cohorts. An administrator can compare the business metrics of the two cohorts, click-through rates, conversion rates, time-to-purchase, to determine which model produces the best real-world search experience.

== E-commerce Core

The preceding sections focused on the visual search pipeline, which constitutes the research contribution of this thesis. This section provides a concise survey of the e-commerce platform modules that surround and support that pipeline. Each module is given a single paragraph below; none is the primary subject of this thesis, but together they form the functional platform within which the visual search feature operates.

*Catalog Management.* Products are created with fashion-specific metadata fields, style code, season name, material composition, department, and gender target, alongside standard catalogue attributes such as title, description, and publication status. Each product may define variants, sellable configurations combining a size and colour, each with its own SKU, barcode, independent pricing, and physical dimensions, with exactly one variant designated as the master variant displayed on listing pages. Product images support multiple variants with automatic thumbnail generation, and each image may store an embedding vector generated by the ML sidecar. Hierarchical taxonomies organise products into a nested category tree, for example, Clothing, Dresses, Evening Dresses, enabling faceted navigation through the catalogue browser.

*Order Processing.* The ordering module orchestrates the complete customer purchase lifecycle. Carts, the initial state of the Order aggregate, auto-expire after seven days of inactivity through a Hangfire background job that periodically cleans up abandoned carts. Checkout progresses through the five-state forward-only state machine described in Chapter 4: Address, Delivery, Payment, Confirm, and Complete. Order numbers are generated inside database transactions with RepeatableRead isolation to prevent duplicate numbering under concurrent checkout loads, a subtle but critical correctness measure in high-traffic flash-sale scenarios. Each order records the checkout state alongside payment and shipment sub-states tracked independently, enabling partial fulfilment, a customer's order may ship in two batches as inventory becomes available.

*Payment Handling.* The payment module manages the lifecycle of payment intents, the customer's commitment to pay a specified amount, through the state machine presented in Chapter 4. Two gateway providers exist: the Stripe gateway handles real payment processing with webhook signature validation using Stripe's signing secret and built-in idempotency keys that prevent double-charging during network retry scenarios; the Bogus gateway simulates the complete payment lifecycle for development environments, automatically transitioning through states without external API calls. The system maintains its own copy of the payment state in parallel with the gateway's representation, enabling offline access to payment status and consistent behaviour across both gateway implementations.

*Inventory Tracking.* Stock quantities are tracked per variant per warehouse location with two separate counters: on-hand quantity, representing the physical stock count, and reserved quantity, representing units held for active checkouts. The invariant `QuantityOnHand >= 0` is enforced at the domain entity level, preventing negative stock states. Stock reservations are acquired through atomic transactions using row-level pessimistic locking, a `SELECT FOR UPDATE` that serialises concurrent access to the same inventory row. When two customers attempt to purchase the last unit of a product, the database lock ensures sequential execution, and the second request receives a graceful out-of-stock rejection. Every stock change, whether from receiving, selling, returning, or stocktaking, is recorded as a StockMovement entry in an append-only ledger with the quantity before and after, the reason, and the operating user.

*Background Automation.* Hangfire serves as the background job processor, executing scheduled and on-demand tasks that are not part of the synchronous request-response cycle. Cart expiry jobs run on a twenty-minute interval, removing carts with no activity for seven days. Embedding generation retries handle transient failures when the ML sidecar is briefly unavailable, failed embedding requests are queued for retrial with exponential back-off. Periodic index maintenance rebuilds or optimises HNSW indices on the vector column to keep nearest-neighbour search performance stable as the catalogue grows. All jobs are persisted in Redis, ensuring that scheduled work survives application restarts and container reorganisations.
