=== Database Design

The ReSys.Shop database is a single PostgreSQL 17 instance organised into per-context schemas, each owned by a bounded context and managed through Entity Framework Core migrations. This section describes the schema organisation, the core entity-relationship model, the pgvector integration for visual search, and the key design decisions that shape the data layer.

==== Schema Organisation

Each of the eight bounded contexts owns its database schema. The Catalog context manages tables for products, variants, variant images, option types, option values, taxonomies, and taxons. The Ordering context owns orders, line items, adjustments, shipments, and inventory units. The Payment context holds payment intents, payment captures, and payment logs. The Inventory context manages stock locations, stock items, stock movements, and stock reservations. The Identity context, built on ASP.NET Identity Core, manages users, roles, user roles, refresh tokens, and external login providers. The Profile context owns user addresses, wishlists, and notification preferences. The Shipping context manages shipping methods, shipping rates, and shipping zones. The Location context provides country and state reference tables.

Cross-context relationships are implemented through identifier references only, there are no foreign key constraints spanning module boundaries. An Order references a UserId (Identity context) and a VariantId (Catalog context), but these are stored as UUIDs without database-level referential integrity constraints. This design preserves the logical isolation of each context as a separate schema while keeping all data in a single database, avoiding the complexity of distributed transactions for the most common business operations.

Entity Framework Core manages all migrations from a dedicated Migrations assembly. Each migration is generated by comparing the current database state against the domain entity model, and migrations are applied as part of the application startup or through standalone migration scripts for production deployments.

==== Core Entity-Relationship Model

@fig-erd-core presents the entity-relationship diagram for the core business entities across all eight bounded contexts, their key attributes, primary and foreign keys, and the relationships within and between contexts. Cross-context relationships (dotted lines) use identifier references only, without database-level foreign key constraints.

#set figure.caption(position: top)
#rotate(-90deg, reflow: true)[
  #figure(
    image("../../../../figures/chapters/part2/ch2-design/03-architecture/diagrams/P2S2.2.3_erd-core.png", width: 23cm),
    caption: [Core entity-relationship model across all eight bounded contexts.],
  ) <fig-erd-core>
]

The Catalog domain centres on the Product entity, which has a one-to-many relationship with Variant. Each Variant represents a specific sellable configuration, for example, "Cotton T-Shirt, Red, Large", with its own SKU, pricing, and inventory tracking flag. Exactly one variant per product is designated as the master variant. Variants relate one-to-many to VariantImages, each of which holds a file path and an optional `embedding` column of type `vector(512)` for pgvector similarity search. Products configure option types, such as Colour or Size, which in turn define option values. Taxonomies contain taxons in a hierarchical structure, with taxons referencing themselves through a parent foreign key to represent tree structures such as "Clothing → Dresses → Evening Dresses". Products are classified by taxons through a many-to-many classification table.

The Ordering domain centres on the Order entity, which has a one-to-many relationship with LineItem. Each line item references a specific variant, not a product directly, because customers purchase specific configurations. The line item captures a price snapshot at the time of purchase, ensuring that historical orders are unaffected by catalogue price changes. Orders are related to users through a UserId reference, optionally nullable to support guest checkout, and track a session identifier for mapping anonymous carts before authentication.

==== pgvector Integration

PostgreSQL's *pgvector* extension @pgvector2023 executes vector similarity searches directly within the relational engine. The `variant_images` table stores feature vectors in an `embedding` column defined as `vector(512)`. Two approximate nearest neighbour (ANN) index types support distinct operational profiles:

- *HNSW (Hierarchical Navigable Small World)* @malkov2018efficient: Constructs a multi-layer graph where nodes connect locally and hierarchically.
  - *Query Speed:* Logarithmic search complexity; under 2 ms on 100 000-vector corpora.
  - *Build Cost:* Memory-intensive construction, ideal for read-heavy production workloads.
  - *Recall:* Delivers 95--99 percent recall at standard configurations (`ef_search = 100`).

- *IVFFlat (Inverted File with Flat Compression):* Partitions vector space into k-means clusters for targeted inverted list searches.
  - *Query Speed:* Slightly higher latency than HNSW due to cluster probe scans.
  - *Build Cost:* Rapid index creation with minimal memory overhead, optimal for frequent rebuilds or constrained hardware.
  - *Recall:* Achieves comparable recall when configured with optimal probes (`lists = sqrt(n)`, `probes = sqrt(lists)`).

The platform defaults to *HNSW* with cosine distance to meet the sub-second CBIR latency target (NFR-01a). *IVFFlat* serves as the fallback for local or GPU-constrained environments prioritising rapid index rebuilds over raw query throughput.

- *Cosine Distance:* Query operator (`<=>`) measures angular distance. Results rank by similarity score `1 - cosine_distance`, filtering against a configurable default threshold of 0.70.
- *Model Isolation:* Every record includes a `model_name` string (e.g., `"Fashion-CLIP"`). Search queries filter by active model name to enforce strict mathematical alignment across visual embeddings.

==== Key Design Decisions

Several design decisions govern the database layer and influence every bounded context:

*Universally Unique Identifiers.* All primary keys are UUIDs (GUIDs in .NET terminology). This decision eliminates reliance on a central sequence generator, allows safe distributed key generation, useful for client-side offline creation of cart or draft-order records, and prevents the information leakage inherent in auto-incrementing integer primary keys.

*Soft Deletion.* Most domain entities carry an `IsDeleted` boolean column. Entity Framework Core applies a global query filter that excludes soft-deleted rows from all standard queries. This preserves referential integrity, a deleted product does not orphan its historical orders, while keeping the active working set clean. Deleted entities can be restored by administrators if the deletion was in error.

*Audit Columns.* Every entity inherits `CreatedAtUtc` and `ModifiedAtUtc` timestamp columns from the `Entity` base class, populated automatically by an EF Core save interceptor. These columns support chronological analysis of catalogue changes, order lifecycle auditing, and debugging data anomalies without external logging correlation.

*Composite Indexes.* Tables serving high-frequency query patterns carry composite indexes tuned to their access patterns. The Orders table includes `(UserId, Status)` for listing a customer's orders filtered by state, and `(SessionId, Status)` for resolving anonymous carts. These composite indexes avoid the need for separate single-column indexes and reduce disk footprint.

*Variable Vector Dimensions.* Different embedding models produce vectors of different dimensionalities: 384 for DINOv2-S, 512 for Fashion-CLIP and CLIP, 768 for DINOv2-B, 1280 for EfficientNet-B0, and 2048 for ResNet-50. PostgreSQL's `vector` type supports this variability, the dimension is part of the column type declaration, and HNSW indexes are built per-dimension. The system stores embeddings from all models in separate rows, each tagged with the model name, and queries against the active model's dimension only.

==== Per-Context Schema Description

The Identity context stores user accounts with Argon2-hashed passwords, security stamps for session invalidation, and refresh tokens with one-time-use semantics. Role and UserRole tables implement RBAC, while UserLogin records link local accounts to external OAuth providers. UserAddresses store shipping and billing locations with ISO country codes.

The Catalog context's Product table carries fashion-specific metadata columns, style code, season name, material composition, department, and gender target, alongside standard catalogue fields. Variants hold SKU, barcode, cost and selling price in decimal precision, and physical dimensions for shipping calculations. The OptionType and OptionValue tables implement an EAV-lite pattern, allowing administrators to define new product attributes without schema migrations. Taxons use a nested set model with left and right bounds, enabling single-query subtree retrieval for mega-menus and breadcrumb navigation.

The Ordering context stores financial values as decimal with 18-digit precision and 2-decimal scale, avoiding floating-point accumulation errors in tax and discount calculations. Orders maintain separate subtotals for items, adjustments, and shipping, with the total computed as their sum. LineItems capture price snapshots at purchase time, decoupling order history from catalogue changes. OrderHistory provides an append-only audit trail of every state transition.

The Inventory context tracks stock items at a variant-location granularity, with `QuantityOnHand` and `QuantityReserved` maintained as separate counters and protected by optimistic concurrency control using PostgreSQL's `xmin` system column. StockMovements form an immutable ledger, every quantity change, whether from receiving, selling, returning, or stock-taking, is recorded with the delta, balances before and after, unit cost, and an external reference such as an order number or purchase order identifier.
