import type { Country, State } from './ILocationReferenceRepository'

export const mockCountries: Country[] = [
  { id: 'US', name: 'United States', isoCode: 'US' },
  { id: 'CA', name: 'Canada', isoCode: 'CA' },
  { id: 'GB', name: 'United Kingdom', isoCode: 'GB' },
  { id: 'AU', name: 'Australia', isoCode: 'AU' },
  { id: 'DE', name: 'Germany', isoCode: 'DE' },
  { id: 'FR', name: 'France', isoCode: 'FR' },
  { id: 'JP', name: 'Japan', isoCode: 'JP' },
]

export const mockStates: State[] = [
  { id: 'US-AL', name: 'Alabama', isoCode: 'AL', countryId: 'US' },
  { id: 'US-AK', name: 'Alaska', isoCode: 'AK', countryId: 'US' },
  { id: 'US-AZ', name: 'Arizona', isoCode: 'AZ', countryId: 'US' },
  { id: 'US-AR', name: 'Arkansas', isoCode: 'AR', countryId: 'US' },
  { id: 'US-CA', name: 'California', isoCode: 'CA', countryId: 'US' },
  { id: 'US-CO', name: 'Colorado', isoCode: 'CO', countryId: 'US' },
  { id: 'US-CT', name: 'Connecticut', isoCode: 'CT', countryId: 'US' },
  { id: 'US-FL', name: 'Florida', isoCode: 'FL', countryId: 'US' },
  { id: 'US-GA', name: 'Georgia', isoCode: 'GA', countryId: 'US' },
  { id: 'US-HI', name: 'Hawaii', isoCode: 'HI', countryId: 'US' },
  { id: 'US-IL', name: 'Illinois', isoCode: 'IL', countryId: 'US' },
  { id: 'US-NY', name: 'New York', isoCode: 'NY', countryId: 'US' },
  { id: 'US-TX', name: 'Texas', isoCode: 'TX', countryId: 'US' },
  { id: 'CA-AB', name: 'Alberta', isoCode: 'AB', countryId: 'CA' },
  { id: 'CA-BC', name: 'British Columbia', isoCode: 'BC', countryId: 'CA' },
  { id: 'CA-MB', name: 'Manitoba', isoCode: 'MB', countryId: 'CA' },
  { id: 'CA-NB', name: 'New Brunswick', isoCode: 'NB', countryId: 'CA' },
  { id: 'CA-ON', name: 'Ontario', isoCode: 'ON', countryId: 'CA' },
  { id: 'CA-QC', name: 'Quebec', isoCode: 'QC', countryId: 'CA' },
  { id: 'GB-ENG', name: 'England', isoCode: 'ENG', countryId: 'GB' },
  { id: 'GB-SCT', name: 'Scotland', isoCode: 'SCT', countryId: 'GB' },
  { id: 'GB-WLS', name: 'Wales', isoCode: 'WLS', countryId: 'GB' },
  { id: 'GB-NIR', name: 'Northern Ireland', isoCode: 'NIR', countryId: 'GB' },
  { id: 'AU-NSW', name: 'New South Wales', isoCode: 'NSW', countryId: 'AU' },
  { id: 'AU-VIC', name: 'Victoria', isoCode: 'VIC', countryId: 'AU' },
  { id: 'AU-QLD', name: 'Queensland', isoCode: 'QLD', countryId: 'AU' },
  { id: 'AU-WA', name: 'Western Australia', isoCode: 'WA', countryId: 'AU' },
  { id: 'AU-SA', name: 'South Australia', isoCode: 'SA', countryId: 'AU' },
  { id: 'DE-BW', name: 'Baden-Württemberg', isoCode: 'BW', countryId: 'DE' },
  { id: 'DE-BY', name: 'Bavaria', isoCode: 'BY', countryId: 'DE' },
  { id: 'DE-BE', name: 'Berlin', isoCode: 'BE', countryId: 'DE' },
  { id: 'DE-NW', name: 'North Rhine-Westphalia', isoCode: 'NW', countryId: 'DE' },
  { id: 'FR-IDF', name: 'Île-de-France', isoCode: 'IDF', countryId: 'FR' },
  { id: 'FR-ARA', name: 'Auvergne-Rhône-Alpes', isoCode: 'ARA', countryId: 'FR' },
  { id: 'FR-OCC', name: 'Occitanie', isoCode: 'OCC', countryId: 'FR' },
  { id: 'FR-PAC', name: "Provence-Alpes-Côte d'Azur", isoCode: 'PAC', countryId: 'FR' },
  { id: 'JP-13', name: 'Tokyo', isoCode: '13', countryId: 'JP' },
  { id: 'JP-27', name: 'Osaka', isoCode: '27', countryId: 'JP' },
  { id: 'JP-23', name: 'Aichi', isoCode: '23', countryId: 'JP' },
  { id: 'JP-14', name: 'Kanagawa', isoCode: '14', countryId: 'JP' },
]
