using Pgvector;

namespace Module.Catalog.Domain.Products.Variants.Images.Embeddings;

public static class ImageEmbeddingMethod
{
    #region Factory Methods
    /// <summary>
    /// Creates a new image embedding from ML model output.
    /// </summary>
    /// <param name="variantImageId">The parent variant image identifier.</param>
    /// <param name="modelName">The name of the ML model that generated the embedding.</param>
    /// <param name="modelVersion">The version of the ML model.</param>
    /// <param name="vectorData">The float array representing the embedding vector.</param>
    /// <returns>The created ImageEmbedding entity.</returns>
    // Contract: pre=variantImageId!=Guid.Empty&&modelName!=null&&vectorData!=null,
    //           post=entity.Vector!=null&&entity.Dimensions==vectorData.Length, throws=ArgumentException
    public static ImageEmbedding Create(
        Guid variantImageId,
        string modelName,
        string modelVersion,
        float[] vectorData)
    {
        return new ImageEmbedding
        {
            Id = Guid.NewGuid(),
            VariantImageId = variantImageId,
            ModelName = modelName,
            ModelVersion = modelVersion,
            Vector = new Vector(vectorData),
            Dimensions = vectorData.Length
        };
    }

    /// <summary>
    /// Creates a new image embedding in the Pending status for deferred ML processing.
    /// </summary>
    /// <param name="variantImageId">The parent variant image identifier.</param>
    /// <param name="modelName">The name of the ML model.</param>
    /// <param name="modelVersion">The version of the ML model.</param>
    /// <returns>The created ImageEmbedding entity.</returns>
    public static ImageEmbedding CreatePending(
        Guid variantImageId,
        string modelName,
        string modelVersion)
    {
        return new ImageEmbedding
        {
            Id = Guid.NewGuid(),
            VariantImageId = variantImageId,
            ModelName = modelName,
            ModelVersion = modelVersion,
            Vector = new Vector(Array.Empty<float>()),
            Dimensions = 0,
            Status = EmbeddingStatus.Pending
        };
    }
    #endregion

    #region Lifecycle

    /// <summary>
    /// Resets a Completed or Failed embedding back to Pending for reprocessing.
    /// </summary>
    /// <param name="embedding">The embedding to reset.</param>
    /// <returns>The embedding when resettable; otherwise the current embedding untouched.</returns>
    public static Result<ImageEmbedding> MarkPending(ImageEmbedding embedding)
    {
        if (embedding.Status != EmbeddingStatus.Completed && embedding.Status != EmbeddingStatus.Failed)
            return Result<ImageEmbedding>.Ok(embedding);

        embedding.Status = EmbeddingStatus.Pending;
        embedding.Error = null;
        embedding.HangfireJobId = null;
        embedding.CompletedAtUtc = null;
        return Result<ImageEmbedding>.Ok(embedding);
    }

    /// <summary>
    /// Transitions a Pending embedding to Processing.
    /// </summary>
    /// <param name="embedding">The embedding to transition.</param>
    /// <returns>The embedding on success, or an invalid status transition error.</returns>
    public static Result<ImageEmbedding> MarkProcessing(ImageEmbedding embedding)
    {
        if (embedding.Status != EmbeddingStatus.Pending)
            return ImageEmbeddingResult.Errors.InvalidStatusTransition(
                embedding.Id, embedding.Status, EmbeddingStatus.Processing);

        embedding.Status = EmbeddingStatus.Processing;
        return Result<ImageEmbedding>.Ok(embedding);
    }

    /// <summary>
    /// Transitions a Processing embedding to Completed with the ML output.
    /// </summary>
    /// <param name="embedding">The embedding to transition.</param>
    /// <param name="vector">The embedding vector generated by the ML model.</param>
    /// <param name="dimensions">The dimensionality of the embedding vector.</param>
    /// <param name="modelVersion">The version of the ML model that produced the vector.</param>
    /// <returns>The embedding on success, or an invalid status transition error.</returns>
    public static Result<ImageEmbedding> MarkCompleted(
        ImageEmbedding embedding, float[] vector, int dimensions, string modelVersion)
    {
        if (embedding.Status != EmbeddingStatus.Processing)
            return ImageEmbeddingResult.Errors.InvalidStatusTransition(
                embedding.Id, embedding.Status, EmbeddingStatus.Completed);

        embedding.Status = EmbeddingStatus.Completed;
        embedding.Vector = new Vector(vector);
        embedding.Dimensions = dimensions;
        embedding.ModelVersion = modelVersion;
        embedding.CompletedAtUtc = DateTimeOffset.UtcNow;
        embedding.Error = null;
        return Result<ImageEmbedding>.Ok(embedding);
    }

    /// <summary>
    /// Transitions a Processing embedding to Failed with an error message.
    /// </summary>
    /// <param name="embedding">The embedding to transition.</param>
    /// <param name="error">The error that caused the failure.</param>
    /// <returns>The embedding on success, or an invalid status transition error.</returns>
    public static Result<ImageEmbedding> MarkFailed(ImageEmbedding embedding, string error)
    {
        if (embedding.Status != EmbeddingStatus.Processing)
            return ImageEmbeddingResult.Errors.InvalidStatusTransition(
                embedding.Id, embedding.Status, EmbeddingStatus.Failed);

        embedding.Status = EmbeddingStatus.Failed;
        embedding.Error = error;
        embedding.CompletedAtUtc = DateTimeOffset.UtcNow;
        return Result<ImageEmbedding>.Ok(embedding);
    }

    #endregion
}