using Pgvector;

using Shared.Application.Domain.Models;

namespace Module.Catalog.Domain.Products.Variants.Images.Embeddings;

/// <summary>
/// Represents a vector embedding generated by an ML model for a specific product image.
/// </summary>
// Invariant: ModelName != null; Dimensions > 0; VariantImageId != Guid.Empty
public sealed partial class ImageEmbedding : Entity
{
    #region Properties
    public string ModelName { get; set; } = string.Empty;
    public string ModelVersion { get; set; } = string.Empty;

    /// <summary>
    /// Vector data (pgvector compatibility).
    /// </summary>
    public Vector Vector { get; set; } = new(Array.Empty<float>());
    public int Dimensions { get; set; }

    /// <summary>Current processing status of the embedding.</summary>
    public EmbeddingStatus Status { get; set; } = EmbeddingStatus.Completed;

    /// <summary>Error message when Status is Failed.</summary>
    public string? Error { get; set; }

    /// <summary>Hangfire job identifier for correlation and status polling.</summary>
    public string? HangfireJobId { get; set; }

    /// <summary>Timestamp when the embedding completed (UTC).</summary>
    public DateTimeOffset? CompletedAtUtc { get; set; }
    #endregion Properties

    #region Relationships
    public Guid VariantImageId { get; set; }
    public VariantImage VariantImage { get; set; } = null!;
    #endregion Relationships

    #region Constructor
    internal ImageEmbedding() { }
    #endregion Constructor
}