using Pgvector;

using Shared.Application.Domain.Models;

namespace Module.Catalog.Domain.Products.Variants.Images.Embeddings;

/// <summary>
/// Represents a vector embedding generated by an ML model for a specific product image.
/// </summary>
// Invariant: ModelName != null; Dimensions > 0; VariantImageId != Guid.Empty
public sealed partial class ImageEmbedding : Entity
{
    #region Properties
    public string ModelName { get; set; } = string.Empty;
    public string ModelVersion { get; set; } = string.Empty;

    /// <summary>
    /// Vector data (pgvector compatibility).
    /// </summary>
    public Vector Vector { get; set; } = new(Array.Empty<float>());
    public int Dimensions { get; set; }
    #endregion Properties

    #region Relationships
    public Guid VariantImageId { get; set; }
    public VariantImage VariantImage { get; set; } = null!;
    #endregion Relationships

    #region Constructor
    internal ImageEmbedding() { }
    #endregion Constructor
}