/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Steps: typeof import('primevue/steps')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Password: typeof import('primevue/password')['default']
  const Popover: typeof import('primevue/popover')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Steps: typeof import('primevue/steps')['default']
}