<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Shared.UnitTests</RootNamespace>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Shared/Shared.Foundations/Shared.Foundations.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.Governance/Shared.Governance.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.Platform/Shared.Platform.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.Security/Shared.Security.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.Persistence/Shared.Persistence.csproj" />
    <ProjectReference Include="../../src/Shared/Shared.Integration/Shared.Integration.csproj" />
  </ItemGroup>

</Project>
