@startuml usecase-stock-location-management
left to right direction
skinparam padding 8
skinparam nodesep 40
skinparam ranksep 40

!include _shared/styles.iuml
title UC-ADM-LOC: Stock Location Management

actor "Administrator" as Admin

rectangle "Stock Location Management" {
  usecase "Manage Stock Locations\n[UC-ADM-LOC]" as UC_MAIN
}

Admin --> UC_MAIN

@enduml
