@startuml usecase-authentication

left to right direction

skinparam shadowing false
skinparam dpi 180

<style>

root {
  FontName "Arial"
  FontSize 18
  FontColor #111111
}

actor {
  FontName "Arial"
  FontSize 18
  FontStyle bold
  FontColor #111111
  BackgroundColor #FFFFFF
  LineColor #222222
  LineThickness 2
}

usecase {
  FontName "Arial"
  FontSize 17
  FontColor #111111
  FontStyle plain
  BackgroundColor #FFFFFF
  LineColor #222222
  LineThickness 2
  Padding 18
}

rectangle {
  FontName "Arial"
  FontSize 22
  FontStyle bold
  FontColor #111111
  BackgroundColor #F7F9FA
  LineColor #263238
  LineThickness 3
  RoundCorner 12
  Padding 30
}

arrow {
  FontName "Arial"
  FontSize 15
  FontColor #111111
  LineColor #333333
  LineThickness 2
}

</style>


actor "Customer" as Customer
actor "Email Service" as Email <<system>>
actor "Google OAuth" as Google <<system>>

rectangle {

  ' UC-STR-AUT-REG
  usecase "Register" as UC_REG

  ' UC-STR-AUT-LOGIN
  usecase "Login with Password" as UC_LOGIN

  ' UC-STR-AUT-GOOGLE
  usecase "Login with Google" as UC_GOOGLE

  ' UC-STR-AUT-RESET
  usecase "Reset Password" as UC_RESET

  ' UC-STR-AUT-CHANGE
  usecase "Change Password" as UC_CHANGE

}

Customer --> UC_REG
Customer --> UC_LOGIN
Customer --> UC_GOOGLE
Customer --> UC_RESET
Customer --> UC_CHANGE

UC_REG --> Email : <<communicates>>
UC_RESET --> Email : <<communicates>>
UC_GOOGLE --> Google : <<communicates>>

@enduml