@startuml usecase-user-management
left to right direction
skinparam padding 8
skinparam nodesep 40
skinparam ranksep 40

!include _shared/styles.iuml
title UC-ADM-USR: User Management

actor "Administrator" as Admin

rectangle "User Management" {
  usecase "Manage Users\n[UC-ADM-USR]" as UC_MAIN
}

Admin --> UC_MAIN

@enduml
