@startuml usecase-option-type-config
left to right direction
skinparam padding 8
skinparam nodesep 40
skinparam ranksep 40

!include _shared/styles.iuml
title UC-ADM-OPT: Option Type Configuration

actor "Administrator" as Admin

rectangle "Option Type Configuration" {
  usecase "Manage Option Types\n[UC-ADM-OPT]" as UC_MAIN
}

Admin --> UC_MAIN

@enduml
