@startuml usecase-role-permission

left to right direction

skinparam shadowing false
skinparam dpi 180

<style>

root {
  FontName "Arial"
  FontSize 18
  FontColor #111111
}

actor {
  FontName "Arial"
  FontSize 18
  FontStyle bold
  FontColor #111111
  BackgroundColor #FFFFFF
  LineColor #222222
  LineThickness 2
}

usecase {
  FontName "Arial"
  FontSize 17
  FontColor #111111
  FontStyle plain
  BackgroundColor #FFFFFF
  LineColor #222222
  LineThickness 2
  Padding 18
}

rectangle {
  FontName "Arial"
  FontSize 22
  FontStyle bold
  FontColor #111111
  BackgroundColor #F7F9FA
  LineColor #263238
  LineThickness 3
  RoundCorner 12
  Padding 30
}

arrow {
  FontName "Arial"
  FontSize 15
  FontColor #111111
  LineColor #333333
  LineThickness 2
}

</style>


actor "Administrator" as Admin

rectangle {

  ' UC-ADM-ROL
  usecase "Manage Roles and Permissions" as UC_MAIN

  ' UC-ADM-ROL-ROLE
  usecase "Manage Roles" as UC_ROLES

  ' UC-ADM-ROL-ASSIGN
  usecase "Assign User Roles" as UC_ASSIGN

  ' UC-ADM-ROL-GRANT
  usecase "Grant Direct Permissions" as UC_GRANT

  ' UC-ADM-ROL-CATALOG
  usecase "View Permissions Catalogue" as UC_CATALOG

}

Admin --> UC_MAIN
Admin --> UC_ROLES
Admin --> UC_ASSIGN
Admin --> UC_GRANT
Admin --> UC_CATALOG

@enduml