=== Model Configuration

The ability to switch between embedding models without code changes is a key implementation decision that supports the benchmark evaluation presented in Chapter 3. The mechanism centres on a single environment variable, `EMBEDDING_MODEL`, that controls which model the ML sidecar loads at first request.

The environment variable accepts a short model identifier: `fashion_clip` for the fine-tuned fashion model, `resnet50` for the classic CNN baseline, `efficientnet_b0` for the lightweight scaled CNN, `clip_vit_b32` or `clip_vit_b16` or `clip_vit_l14` for general-purpose CLIP variants, and `dinov2_vits14` or `dinov2_vitb14` for self-supervised vision transformers. When the Model Manager receives its first embedding request, it reads this variable, instantiates the corresponding model class, loads weights from disk, and caches the instance. Subsequent requests are served from the cache. Changing the active model requires updating the environment variable and restarting the container, a configuration-only change with no code modification.

Each stored embedding carries two metadata columns: `model_name`, identifying which model generated the vector, and `model_version`, capturing the weight snapshot used. When the backend queries pgvector for similar images, it filters by `model_name`, only embeddings from the currently active model participate in the search. This filter ensures that the system can store embeddings from multiple models simultaneously, with each model's embeddings occupying a separate conceptual index within the same physical column. After switching the active model, newly uploaded images begin generating embeddings under the new model name, while existing embeddings under the old model name remain available but are excluded from search queries.

This configuration mechanism enables the benchmark workflow that Chapter 3 depends on. Eleven models are evaluated against the same image corpus by loading each model in sequence, generating embeddings for the full query and catalogue image sets, running the retrieval evaluation protocol, and recording the results, all without modifying application code. In production, the same mechanism enables A/B testing: two instances of the ML sidecar, each configured with a different model, serve embedding requests to different user cohorts. An administrator can compare the business metrics of the two cohorts, click-through rates, conversion rates, time-to-purchase, to determine which model produces the best real-world search experience.
