==== Catalog Management

#figure(
  table(
    columns: (auto, auto, auto, 1fr, auto, 1fr),
    stroke: 0.5pt,
    table.header([*UC-ID*], [*Use Case*], [*Actor*], [*Flow*], [*Postcondition*], [*Related FR*]),
    [UC-ADM-CAT-01], [Create product], [Admin],
    [Enter product details (name, description, slug, fashion metadata), define at least one master variant with SKU and price, upload images, assign taxons.],
    [Product created with Draft status; master variant available for catalog operations.],
    [CAT-FR-01, CAT-FR-02, CAT-FR-03, CAT-FR-13],
    [UC-ADM-CAT-02], [Update product], [Admin],
    [Modify any product field (description, metadata, status, SEO fields). Slug changes validated for uniqueness.],
    [Product updated; if status changed to Archived, hidden from storefront.],
    [CAT-FR-01, CAT-FR-12],
    [UC-ADM-CAT-03], [Delete product], [Admin],
    [Soft-delete product and all associated variants, images, and classifications.],
    [Product flagged as deleted; not recoverable through storefront.],
    [CAT-FR-01],
    [UC-ADM-CAT-04], [Add variant], [Admin],
    [Select parent product, define SKU, barcode, dimensions, weight, and pricing; assign option values (Size M + Colour Red) to specify the variant configuration.],
    [Variant created and available for inventory tracking, pricing, and image assignment.],
    [CAT-FR-03, CAT-FR-21, CAT-FR-22],
    [UC-ADM-CAT-05], [Upload variant images], [Admin],
    [Select variant, upload image file, set alt text and display order. System triggers embedding generation job.],
    [Image stored with metadata; embedding generation queued as background job.],
    [CAT-FR-04, CAT-FR-05, CAT-FR-15],
    [UC-ADM-CAT-06], [Regenerate embeddings], [Admin],
    [Select variant images and trigger embedding regeneration for the currently configured model.],
    [New embeddings generated and stored in pgvector with updated model metadata.],
    [CAT-FR-05, CAT-FR-08, CAT-FR-15],
    [UC-ADM-CAT-07], [Manage taxonomies], [Admin],
    [Create, update, or delete taxonomies and nested taxon trees. Reorder taxons within a taxonomy.],
    [Taxonomy structure updated; products classified under affected taxons retain their classifications.],
    [CAT-FR-09],
    [UC-ADM-CAT-08], [Classify products], [Admin],
    [Assign products to one or more taxon nodes. Synchronise or revoke classifications.],
    [Product appears under assigned categories in storefront browsing and search filters.],
    [CAT-FR-09, CAT-FR-19],
    [UC-ADM-CAT-09], [Manage option types], [Admin],
    [Create option types (e.g., Size, Colour) with ordered option values. Assign option types to products.],
    [Option types available for variant configuration across assigned products.],
    [CAT-FR-10, CAT-FR-20],
  ),
  caption: [Administrator use cases for the Catalog module.],
)
