==== Order Fulfilment

#figure(
  table(
    columns: (auto, auto, auto, 1fr, auto, 1fr),
    stroke: 0.5pt,
    table.header([*UC-ID*], [*Use Case*], [*Actor*], [*Flow*], [*Postcondition*], [*Related FR*]),
    [UC-ADM-ORD-01], [View orders], [Admin],
    [List orders with paging, filtering by status, date range, and customer. Drill into individual order detail showing line items, payments, shipments, and history.],
    [Order data displayed with full transactional context.],
    [ORD-FR-05, ORD-FR-06, ORD-FR-13],
    [UC-ADM-ORD-02], [Update order], [Admin],
    [Modify order attributes: add, update, or remove line items; update shipping and billing addresses; change shipping method.],
    [Order updated; totals recalculated to reflect line item and adjustment changes.],
    [ORD-FR-05, ORD-FR-13],
    [UC-ADM-ORD-03], [Approve order], [Admin],
    [Approve a pending order for fulfilment. System verifies payment status and inventory availability.],
    [Order approved and moved to fulfilment queue; inventory reserved if not already held.],
    [ORD-FR-04, ORD-FR-13],
    [UC-ADM-ORD-04], [Complete order], [Admin],
    [Mark order as fulfilled after shipment confirmation. Finalise totals and lock the order against further modification.],
    [Order completed; immutable after this point. Inventory on-hand quantities decremented.],
    [ORD-FR-09, ORD-FR-13],
    [UC-ADM-ORD-05], [Cancel order], [Admin],
    [Cancel an order at any pre-confirmation stage with mandatory reason. Release reserved inventory, void payment intents.],
    [Order cancelled; inventory released; payment voided.],
    [ORD-FR-07],
    [UC-ADM-ORD-06], [Resume order], [Admin],
    [Resume a previously paused or stalled order, moving it back into the active workflow.],
    [Order returned to processing state.],
    [ORD-FR-13],
  ),
  caption: [Administrator use cases for the Ordering module.],
)
