<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>resys.shop.api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Shared/Shared.Foundations/Shared.Foundations.csproj" />
    <ProjectReference Include="../Shared/Shared.Governance/Shared.Governance.csproj" />
    <ProjectReference Include="../Shared/Shared.Platform/Shared.Platform.csproj" />
    <ProjectReference Include="../Shared/Shared.Security/Shared.Security.csproj" />
    <ProjectReference Include="../Shared/Shared.Persistence/Shared.Persistence.csproj" />
    <ProjectReference Include="../Shared/Shared.Integration/Shared.Integration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Module/Module.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Migrations/Api.Migrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>


</Project>