=== Non-Functional Requirements

Five quality dimensions define production-readiness constraints with atomic, measurable targets. Each dimension forms a single requirement group whose identifier (for example, NFR-GRP-01) is used when a design decision refers back to these targets. Verification is assessed in Chapter 3.

#strong[Performance] (NFR-GRP-01). End-to-end CBIR search workflows complete within one second per query, non-search REST endpoints respond within 200 milliseconds under standard load, and asynchronous I/O is enforced across all data-access and HTTP pipelines.

#strong[Security] (NFR-GRP-02). JWT access tokens @jones2015jwt expire after 15 minutes with single-use refresh token rotation, and fine-grained claims (domain.category.resource.action) are enforced at the API middleware boundary. Per-IP fixed-window rate limiting protects authentication, registration, password reset, payment, and webhook endpoints; uploads are validated via magic-byte header inspection with extension allowlists and a 10 MB cap; and security headers (CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy) are injected by middleware, with HSTS applied by the reverse-proxy layer in deployment.

#strong[Modularity] (NFR-GRP-03). All business modules compile into one Module assembly with forward-only dependencies (Shared → Module → Api); inter-module behaviour routes through MediatR in-process dispatch where pipeline value (validation, logging, transactions) applies, while direct service calls and navigations are used where they fit the feature slice. Each module is independently testable without initialising foreign contexts.

#strong[Observability] (NFR-GRP-04). OpenTelemetry trace contexts propagate across the .NET API and the Python ML sidecar, structured logging attaches a unique correlation identifier to every log entry, and health monitoring exposes /health/live and /health/ready endpoints verifying database and cache connectivity, alongside the sidecar's own /health and /alive endpoints.

#strong[Reliability] (NFR-GRP-05). Background tasks run on Hangfire @hangfire-docs backed by Redis @redis-docs so they survive process restarts; scheduled maintenance purges carts inactive for 7 days on an hourly job and releases their associated inventory reservations, Stripe webhooks are guarded by idempotency keys against duplicate state updates, and unconfirmed checkout inventory holds expire after 15 minutes of inactivity.