=== Vertical Slice Architecture

The .NET backend is organised according to *Vertical Slice Architecture* (VSA), a pattern in which code is grouped by business capability rather than by technical layer. In a traditional layered architecture, all data access classes reside in one project, all business logic in another, and all web controllers in a third. VSA inverts this convention: all code required to fulfil a single feature, the request, the handler, the response, the validator, is co-located within one directory. This organisation makes the system easier to navigate because a developer tracing a feature through the codebase follows a vertical path rather than jumping across four or five horizontal layers.

The implementation uses Carter minimal APIs for route registration and MediatR for command and query dispatch. Each bounded context, Catalog, Ordering, Payment, and the remaining five modules, contributes its own `ICarterModule` implementation, which registers all endpoints belonging to that context. Endpoints are thin: they extract parameters from the HTTP request, construct a MediatR command or query object, dispatch it through `ISender`, and map the resulting `Result<T>` to an HTTP status code and JSON body. All business logic, database access, and domain invariant enforcement reside in the handler layer, where they are testable without HTTP infrastructure.

FluentValidation ensures that every command and query object is validated before its handler executes. Validation classes live alongside the handlers they protect, keeping the validation rules visible and colocated with the logic they guard. The MediatR pipeline wraps each request with three behaviours, validation, logging, and exception mapping, applied automatically to every handler in the system. A fourth pipeline behaviour enforces feature-level transaction boundaries, ensuring that handlers operating on multiple database rows do so within a single unit of work.

The vertical slice organisation enforces a strict module boundary rule: no bounded context may import another context's namespace. All inter-module communication flows through MediatR's `ISender` interface. A context may dispatch a query to another context or publish a notification that other contexts react to, but it may never reference a class, type, or namespace belonging to another module. This constraint preserves the logical isolation of the bounded contexts, the same isolation that would be enforced by network boundaries in a microservices architecture, while retaining the deployment simplicity of a single process.
