=== Model Configuration

The ML sidecar uses environment-driven configuration to decouple model selection from application code. This mechanism enables model swapping, multi-model embedding storage, and standardized benchmark comparisons without code modifications.

==== Environment-Driven Selection

The core selection mechanism relies on a single #emph("EMBEDDING_MODEL") environment variable. When the Model Manager receives its first inference request, it reads this identifier, instantiates the target model class, loads weight snapshots from disk, and caches the model instance in memory.

The system maps environment configuration strings to four model categories:

- *CNN Baselines:* #emph[resnet50] (2048-dim), #emph("efficientnet_b0") (1280-dim)
- *Vision Transformers:* #emph("dinov2_vits14") (384-dim), #emph("dinov2_vitb14") (768-dim)
- *Multimodal CLIP:* #emph("clip_vit_b32"), #emph("clip_vit_b16"), #emph("clip_vit_l14") (512-dim)
- *Domain-Specific:* #emph("fashion_clip") (512-dim)

Swapping the active inference model requires updating the #emph("EMBEDDING_MODEL") variable and restarting the container instance, a pure configuration change.

==== Metadata Schema & Latent Space Isolation

Each stored vector record maintains explicit metadata to prevent invalid vector distance comparisons:

- *#emph("model_name"):* Identifies the generating model architecture (e.g., #emph("\"Fashion-CLIP\"")).
- *#emph("model_version"):* Captures the specific pre-trained weight snapshot version.

When executing similarity queries via #emph[pgvector], the API backend appends a #emph("model_name") predicate filter to the search query. This isolates embeddings from different models into separate conceptual indices within the same physical #emph[vector] column, allowing embeddings generated by different architectures to coexist in PostgreSQL without cross-model latent space corruption.

==== Benchmarking & A/B Testing Workflows

The configuration architecture supports two critical operational workflows:

1. *Automated Benchmarking:* Enables sequential benchmarking of 11 candidate models across identical image corpora. Test scripts update container environment configurations, generate full vector sets, and run retrieval protocols without altering backend logic.
2. *Production A/B Deployment:* Supports dual ML sidecar instances configured with distinct model identifiers. Traffic routers direct different user cohorts to each sidecar instance, enabling direct comparison of downstream business metrics (e.g., click-through rates, conversion rates, time-to-purchase).